////////////////////////////////////////////////////////////////////////////////
//
//  (c) KAP IT
//  
//  All Rights Reserved.
//
////////////////////////////////////////////////////////////////////////////////

 /**
 * This object hold all the special characters of the
 * keyboard. {keyCode:associateButtion}
 */ 
private var specialkeys:Object = {
	27:'esc',
	9:'tab',
	32:'space',
	13:'return',
	8:'backspace',
	
	16:'shift',
	17:'ctrl',
	18:'alt',

	145:'scrolllock',
	20:'capslock',
	144:'numlock',
	
	19:'break',
	
	45:'insert',
	36:'home',
	46:'delete',
	35:'end',
	
	33:'pageup',

	34:'pagedown',

	37:'left',
	38:'up',
	39:'right',
	40:'down',

	112:'f1',
	113:'f2',
	114:'f3',
	115:'f4',
	116:'f5',
	117:'f6',
	118:'f7',
	119:'f8',
	120:'f9',
	121:'f10',
	122:'f11',
	123:'f12',
	
	96:'0',
	97:'1',
	98:'2',
	99:'3',
	100:'4',
	101:'5',
	102:'6',
	103:'7',
	104:'8',
	105:'9'
}